### PR TITLE
try a windows build

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by jdblischak** [comment]
@izahn Thanks for giving this a shot. Looks like it is still the same [error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=515288&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=484) as I had previously documented in #20. Any ideas what the issue could be or how we could fix it?

**Comment by izahn** [comment]
googlng the error message brings up https://github.com/msys2/MSYS2-packages/issues/171 and  https://github.com/msys2/MINGW-packages/issues/4528 among other things.

**Comment by mbargull** [comment]
fixed via gh-33

**Pull request closed without merging**
