### PR TITLE
Update r-xml to 3.98-1.9

### PR DESCRIPTION
**Pull request by ccwang002**

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Can we merge this pull request?

**Comment by ccwang002** [comment]
The PR itself should be good to merge, though I don't know if we want a newer one since it's been a while.

**Comment by ccwang002** [comment]
@conda-forge-admin any chance this get merged? Thanks!

**Comment by ccwang002** [comment]
@conda-forge/core i think this pull request is too old to be merged, but it might be good to upgrade this package to a new version

**Comment by scopatz** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Sorry we missed this one. Let's go for the latest version in #2

**Pull request closed without merging**
