### PR TITLE
Re-enable Windows builds

### LINKED ISSUE #32: @conda-forge-admin, please rerender
### Additional comment:

Want to try a thing regarding the Windows build.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #32.

Here's a checklist to do before merging.
- [x] Bump the build number if needed. (not needed since other platforms recently rebuilt)

Fixes #32, #20, #27

### CODE REVIEW

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
@conda-forge-admin, please rerender

**Comment by mbargull** [comment]
The reason why the Windows builds were not working since gh-19 was essentially a missing dependency.
Prior to gh-19, it linked to `m2w64-libxml2` which gets indirectly pulled in via `r-base` but is not declare as a direct depedency (instead of `libxml2`).
By the time gh-19 got around, there was a change at https://github.com/conda-forge/libxml2-feedstock/pull/54 which lead to `libxml2`'s `xml2.lib` being picked up instead of `m2w64-libxml2`'s one (which caused the observed linking failures).

The `Makevars.*` change is needed so that it can find libxml2's headers. It only worked without it before because it took the headers from `libxml2` but then the compiled library from `m2w64-libxml2`. With the added change we avoid that mix-and-match and also don't need the additional `libxml2` dependency.

cc @jdblischak, @izahn

**Comment by jdblischak** [comment]
@mbargull Thanks for fixing this and providing a thorough explanation. Much appreciated!

**Pull request merged**
